SMTP_FROM_USER="no-reply@gydra-test.ru"
export SMTP_FROM_USER
SMTP_HOST="127.0.0.1"
export SMTP_HOST
SMTP_PORT="1025"
export SMTP_PORT
SMTP_DOMAIN="gydra-test.ru"
export SMTP_DOMAIN
SMTP_USE_SSL="no"
export SMTP_USE_SSL
SMTP_USER_NAME=""
export SMTP_USER_NAME
SMTP_PASSWORD=""
export SMTP_PASSWORD
